### PR TITLE
added ng-cloak for avoiding weird placeholder shown while page loaded

### PR DESCRIPTION
**Pull request by emir**

### CODE REVIEW

**Comment by heiglandreas** [comment]
That's all there is to it? That's awesome! Thanks!

**Comment by emir** [comment]
Yeah did you deployed?

**Comment by heiglandreas** [comment]
No, not yet. Deployment is currently not automated :(

**Comment by heiglandreas** [comment]
Ping @lornajane or anyone with access to jenkins - please trigger the callingallpapers-launch. Thanks

**Comment by akrabat** [comment]
Done.

**Comment by heiglandreas** [comment]
Thanks!!!

**Comment by emir** [comment]
Thanks @akrabat!

**Pull request merged**
