### PR TITLE
Integrated Grunt

### PR DESCRIPTION
**Pull request by AurelioDeRosa**

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
This PR depends on #21.

**Comment by heiglandreas** [comment]
Thanks for the PR @AurelioDeRosa but can you give us a bit more information as how to implement/use the grunt-file? Will it just be "call grunt instead of phing"? Or is there more to it? I currently can't see what impact the change has on the deployment and the development toolage.

**Comment by AurelioDeRosa** [comment]
Hi @heiglandreas. The process would be:

```
npm install
grunt
```

The first command install all the dependencies for the task runner. The second execute the optimizations. In particular it creates a new directory called `dist` that has all the CSS and JS files concatenated and minified. In addition it adds a hash to the name of the files to improve how the browsers will cache the assets. I also kept JSHint that was in the old configuration.

Thank you to this PR, the website will perform 8 HTTP requests less.

**Comment by AurelioDeRosa** [comment]
Any news about this PR?

**Comment by heiglandreas** [comment]
Sorry, had a busy week. I'll check that stuff tomorrow evening and let you know!

**Comment by heiglandreas** [comment]
@magicmonkey @lornajane What would have to be done on the deployment-chain to deploy callingallpapers.com via grunt instead of phing? I've checked this PR and would love to merge it but I'm not sure what has to be done on the backend before the changes actually can be used... Any hints?

**Comment by heiglandreas** [comment]
@AurelioDeRosa Thanks for the great work! I've checked it and it works fine. I'm just waiting for the feedback to finally merge it.

**Comment by magicmonkey** [comment]
Good news, grunt is already installed on the server:

```
kevin@joindin:~$ sudo -u jenkins -i grunt --version
grunt-cli v0.1.13

kevin@joindin:~$ sudo -u jenkins -i npm ls -g grunt
/usr/local/lib
└── grunt@0.4.5
```

The only Jenkins job is the launch job (http://jenkins.joind.in/view/All/job/CallingAllPapers_launch) which actually runs a bash script in the codebase (https://github.com/joindin/callingallpapers.com/blob/master/scripts/launch.sh) which runs bower (not phing) and then some symlink-fiddling magic to make the launch atomic.

Feel free to change the `bower install` line in that shell script, if the other bits change then I probably need to care more as that'll affect how it's served on the webserver.  If you want me to do anything else, let me know.

**Comment by AurelioDeRosa** [comment]
Cool @heiglandreas, look forward to it. I think the only commands you have to run on the server, as suggested before, are:

``` bash
npm install
grunt
```

**Comment by heiglandreas** [comment]
Well @AurelioDeRosa that's not everything as it seems. As all the "new" files are located in the `dist`-folder and not in the `public`-folder anymore, @magicmonkey will have to adapt the DocumentRoot in the webserver-configuration. This has to be done only once but it has to be done to get the benefit of this change.

As far as I see it, we can still use the "old" way of deploying the application (using `bower install`) after this PR is merged and then @magicmonkey can change the DocumentRoot at any time he wants from `public` to `dist` to make use of the new grunt-based deployment. 

Or am I missing anything?

**Pull request merged**
